### ISSUE TITLE
Application icon art

### ISSUE THREAD

**Issue by GreyArmor** [GreyArmor/Amoros-Risk#6]
create an application icon for the game

replace this file and it should work

https://github.com/GreyArmor/Amoros-Risk/blob/main/AmorosRisk/Icon.ico

**Comment by AmoraPSN** [comment]
Solved, in art and discord.
![IconBorderedRisk](https://user-images.githubusercontent.com/98931869/152643602-3d35eb86-581d-479f-8ba8-7985cbbb2498.png)
![IconBareRisk](https://user-images.githubusercontent.com/98931869/152643603-29cd1979-5282-4b0f-8081-c78c3a8a2fd3.png)
